# --------------------------------------
# Variables -> main.yaml
# Role: config-rt-protocols
# Create at Thu 15 Jul 2021 16:01:05 EDT
# --------------------------------------

---
routers:
  - router_mgnt: 192.168.1.1
    hostname: C12
    routing_protocols:
      - type: eigrp 
        enable: true
        area: 1
        networks: 
          - 172.16.0.0

  - router_mgnt: 192.168.1.2
    hostname: C13
    routing_protocols:
      - type: eigrp 
        enable: true
        area: 1
        networks: 
          - 172.16.0.0

  - router_mgnt: 192.168.1.3
    hostname: CE1
    routing_protocols:
      - type: eigrp 
        enable: true
        area: 1
        networks: 
          - 1.0.0.0
          - 10.0.0.0
          - 172.16.0.0
        redistributions: 
          - static
          - bgp 1 metric 100 1 255 1 1500
      - type: bgp
        enable: true
        area: 1
        networks: 
          - 1.1.1.1 mask 255.255.255.255
          - 172.16.0.0
        synchronization: true
        links:
          - neighbor: 10.10.1.2
            remote_as: 12
        redistributions: 
          - eigrp 1

  - router_mgnt: 192.168.1.4
    hostname: P
    routing_protocols: 
      - type: ospf
        area: 1
        networks: 
          - 3.3.3.3 0.0.0.0 area 0
          - 10.10.2.0 0.0.0.255 area 0
          - 10.10.3.0 0.0.0.255 area 0

  - router_mgnt: 192.168.1.5
    hostname: PE1
    routing_protocols:
      - type: ospf
        area: 1
        networks:
          - 2.2.2.2 0.0.0.0 area 0
          - 10.10.2.0 0.0.0.255 area 0
      - type: bgp
        area: 12
        links: 
          - neighbor: 4.4.4.4
            remote_as: 12
            next_hop_self: true
          - neighbor: 10.10.1.1
            remote_as: 1
          - neighbor: 10.10.4.2
            remote_as: 12
            next_hop_self: true

  - router_mgnt: 192.168.1.6
    hostname: PE2
    routing_protocols:
      - type: ospf
        area: 1
        networks:
          - 4.4.4.4 0.0.0.0 area 0
          - 10.10.3.0 0.0.0.255 area 0
      - type: bgp 
        area: 12
        links: 
          - neighbor: 2.2.2.2
            remote_as: 12
            next_hop_self: true
          - neighbor: 10.10.1.2
            remote_as: 12
            next_hop_self: true
          - neighbor: 10.10.4.1
            remote_as: 2

  - router_mgnt: 192.168.1.7
    hostname: C22
    routing_protocols:
      - type: eigrp
        area: 2
        networks: 
          - 172.17.0.0

  - router_mgnt: 192.168.1.8
    hostname: CE2
    routing_protocols:
      - type: eigrp
        area: 2
        networks:
          - 5.0.0.0
          - 10.0.0.0
          - 172.17.0.0
        redistributions: 
          - bgp 2 metric 100 1 255 1 1500
      - type: bgp
        area: 2
        synchronization: false
        networks:
          - 5.5.5.5 mask 255.255.255.255
          - 172.17.0.0
        links:
          - neighbor: 10.10.4.2
            remote_as: 12
        redistributions: 
          - eigrp 2

  - router_mgnt: 192.168.1.9
    hostname: C23
    routing_protocols:
      - type: eigrp
        area: 2
        networks: 
          - 172.17.0.0