# --------------------------------------
# Tasks -> main.yaml
# Role: config-ip
# Create at Thu 15 Jul 2021 11:32:18 EDT
# --------------------------------------

---
- name: Generate Configuration
  template:
    dest: "outputs/{{ role_name }}/{{ inventory_hostname }}.txt"
    src: "config.j2"
  with_items: "{{ routers }}"
  when:
    - item.router_mgnt == inventory_hostname

- name: Configure Routers
  cisco.ios.ios_config:
    src: "../outputs/{{ role_name }}/{{ inventory_hostname }}.txt"
    diff_against: "running"
    backup: yes
  with_items: "{{ routers }}"
  when: 
    - item.router_mgnt == inventory_hostname 

