# --------------------------------------
# Tasks -> main.yaml
# Role: isp
# Create at Wed Jul 14 13:28:15 EDT 2021
# --------------------------------------

---
- name: Generate Configuration
  template:
    dest: "G10-OUTPUTS/{{ role_name }}/{{ inventory_hostname }}.txt"
    src: "config.j2"
  with_items: "{{ routers }}"
  when:
    - item.router_mgnt == inventory_hostname

- name: Configure Routers
  cisco.ios.ios_config:
    src: "../G10-OUTPUTS/{{ role_name }}/{{ inventory_hostname }}.txt"
  with_items: "{{ routers }}"
  when: 
   - item.router_mgnt == inventory_hostname 