# --------------------------------------
# Tasks -> main.yaml
# Role: bring-up-interface
# Create at Thu 29 Jul 2021 15:38:16 EDT
# --------------------------------------

---
- name: Generate Configuration
  template:
    dest: "G10-OUTPUTS/{{ role_name }}/{{ inventory_hostname }}.txt"
    src: "config.j2"
  with_items: "{{ routers }}"
  when:
    - item.router_mgnt == inventory_hostname

- name: Configure Routers
  cisco.ios.ios_config:
    src: "../G10-OUTPUTS/{{ role_name }}/{{ inventory_hostname }}.txt"
    diff_against: "running"
  with_items: "{{ routers }}"
  when: 
    - item.router_mgnt == inventory_hostname 