# --------------------------------------
# Tasks -> main.yaml
# Role: enterprise2
# Create at Tue Jul 13 18:42:01 EDT 2021
# --------------------------------------

---
- name: Generate Configuration
  template:
    dest: "G10-OUTPUTS/{{ role_name }}/{{item.hostname}}.txt"
    src: "config.j2"
  with_items: "{{ routers }}"
  when:
    - item.router_mgnt == inventory_hostname

- name: Configure Routers
  cisco.ios.ios_config:
    src: "../G10-OUTPUTS/{{ role_name }}/{{item.hostname}}.txt"
  with_items: "{{ routers }}"
  when: 
   - item.router_mgnt == inventory_hostname 