# --------------------------------------
# Variables -> main.yaml
# Role: bring-up-interface
# Create at Thu 29 Jul 2021 15:38:16 EDT
# --------------------------------------

# default: bring up all interfaces of a router
---
routers:
  - router_mgnt: 192.168.1.1
    interfaces: 
      - name: g0/1 
        enable: true
      - name: g0/2 
        enable: true

  - router_mgnt: 192.168.1.2
    interfaces: 
      - name: g0/1
        enable: true
      - name: g0/2
        enable: true

  - router_mgnt: 192.168.1.3
    interfaces: 
      - name: lo0
        enable: true
      - name: g0/1
        enable: true
      - name: g0/2
        enable: true
      - name: g0/3
        enable: true

  - router_mgnt: 192.168.1.4
    interfaces: 
      - name: lo0
        enable: true
      - name: g0/1
        enable: true
      - name: g0/2
        enable: true

  - router_mgnt: 192.168.1.5
    interfaces: 
      - name: lo0
        enable: true
      - name: g0/2
        enable: true
      - name: g0/3
        enable: true

  - router_mgnt: 192.168.1.6
    interfaces: 
      - name: lo0
        enable: true
      - name: g0/1
        enable: true
      - name: g0/3
        enable: true

  - router_mgnt: 192.168.1.7
    interfaces: 
      - name: g0/1
        enable: true
      - name: g0/2
        enable: true

  - router_mgnt: 192.168.1.8
    interfaces: 
      - name: lo0
        enable: true
      - name: g0/1
        enable: true
      - name: g0/2
        enable: true
      - name: g0/3
        enable: true

  - router_mgnt: 192.168.1.9
    interfaces: 
      - name: g0/1
        enable: true
      - name: g0/2
        enable: true
